CREATE TABLE BatchType (
	Id INTEGER PRIMARY KEY AUTOINCREMENT,
	CreateDate TEXT NOT NULL,
	LastUpdateDate TEXT NOT NULL,
	Inactive INTEGER NOT NULL,
	Name TEXT NOT NULL,
	Description TEXT NOT NULL
);

CREATE TABLE Batch (
	Id INTEGER PRIMARY KEY AUTOINCREMENT,
	CreateDate TEXT NOT NULL,
	LastUpdateDate TEXT NOT NULL,
	Inactive INTEGER NOT NULL,
	Name TEXT NOT NULL,
	BatchTypeId INTEGER NOT NULL,
	FOREIGN KEY(BatchTypeId) REFERENCES BatchType(Id)
);

CREATE TABLE Transistor (
	Id INTEGER PRIMARY KEY AUTOINCREMENT,
	CreateDate TEXT NOT NULL,
	LastUpdateDate TEXT NOT NULL,
	Inactive INTEGER NOT NULL,
	Idx INTEGER NOT NULL,
	HEF REAL NOT NULL,
	Beta REAL NOT NULL,
	BatchId INTEGER NOT NULL,
	GroupId TEXT,
	FOREIGN KEY(BatchId) REFERENCES Batch(Id)
);

